# Generated by Django 4.2.6 on 2023-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_very',
            new_name='email_verified',
        ),
    ]
