# Generated by Django 4.2.6 on 2023-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scheduledemails',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='cupon',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='ScheduledEmails',
        ),
    ]
