# Generated by Django 4.2.6 on 2023-12-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_scheduledemails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cupon',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
