# Generated by Django 4.2.6 on 2023-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_company_cupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cupon',
            new_name='coupon',
        ),
    ]
