# Generated by Django 4.2.6 on 2023-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_smscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
