# Generated by Django 4.2.6 on 2023-12-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_defaultcompany_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcompany',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
