# Generated by Django 4.2.6 on 2024-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_subscriber_subscribed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
